# Configuração Geral do Mosquitto para o CIRCE Home Platform
listener 1883 0.0.0.0
allow_anonymous true

# Configurações de Persistência
persistence true
persistence_location /mosquitto/data/

# Logs do Broker
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all
